### PR TITLE
Fix a bug in memory platforms with redundant also

### LINKED ISSUE #631: MemoryPlatform with unneeded .also can produce double writes
In a case that looks like:

```scala
val b = a.map(fn).sumByKey(store1)
val c = b.map(gn).sumByKey(store2)
b.also(c)
```
the also is not needed, since c already depends on b. It seems having it there is causing double counting.

### PR DESCRIPTION
**Pull request by johnynek**
This adds the tests in #645, verifies that bug manifests, then I fixed the bug. Seems to fix #631 for real. /cc @pankajroark

### CODE REVIEW

**Comment by johnynek** [comment]
It also fixes #646

File: summingbird-core/src/main/scala/com/twitter/summingbird/Dependants.scala [hunk 1]
```diff
@@ -42,14 +42,16 @@ case class Dependants[P <: Platform[P]](tail: Producer[P, Any]) extends Dependan
...
+   * This will include no MergedProducer or AlsoProducer nodes, but all dependencies
+   * of the returned nodes will be Merged, Alsos or the argument.
+   * The purpose of this method is for source-down platforms
+   * that plan from sources to all their dependants recursively.
    */
   def dependantsAfterMerge(inp: Producer[P, Any]): List[Producer[P, Any]] =
     dependantsOf(inp).getOrElse(Nil).flatMap {
       case m @ MergedProducer(_, _) => dependantsAfterMerge(m)
-      case AlsoProducer(_, r) => dependantsAfterMerge(r)
+      case a @ AlsoProducer(_, _) => dependantsAfterMerge(a)
```
Comment (johnynek) [inline summingbird-core/src/main/scala/com/twitter/summingbird/Dependants.scala]: here is the bug that hits `ConcurrentMemory`.

File: summingbird-core/src/main/scala/com/twitter/summingbird/memory/Memory.scala [hunk 2]
```diff
@@ -82,11 +82,11 @@ class Memory(implicit jobID: JobId = JobId("default.memory.jobId")) extends Plat
           case AlsoProducer(l, r) =>
             //Plan the first one, but ignore it
             val (left, leftM) = toStream(l, jamfs)
+            val (right, rightM) = toStream(r, leftM)
```
Comment (johnynek) [inline summingbird-core/src/main/scala/com/twitter/summingbird/memory/Memory.scala]: here is the bug in Memory producer. You should make the `lforcedEmpty` lazy or be sure to plan the right before you evaluate it. Here I do both since it seemed more correct to plan as much as possible before causing side effects, but also that we don't want side-effects at all until the job is run.

The underlying issue is that `Stream` is not entirely lazy. The head is eager. So, if you do `.filter(_ => false)` there will be no head but it evaluates as much as possible until it finds a head, which means it evaluates the whole stream. By evaluating the steam it hits the side effects in the map functions on `sumByKey` and `write`.

File: summingbird-core/src/main/scala/com/twitter/summingbird/Dependants.scala (hunk 1 above)
Comment (ianoc) [inline summingbird-core/src/main/scala/com/twitter/summingbird/Dependants.scala]: The bug here is that the dependantsOf(p) != r in this case?

Comment (johnynek) [inline summingbird-core/src/main/scala/com/twitter/summingbird/Dependants.scala]: yes, I was looking up the graph, then dependantsOf brought me back down, causing an infinite loop. Wrong direction.

File: summingbird-core/src/main/scala/com/twitter/summingbird/Dependants.scala [hunk 3]
```diff
@@ -42,14 +42,16 @@ case class Dependants[P <: Platform[P]](tail: Producer[P, Any]) extends Dependan
   }
 
   /**
-   * Return the first dependants of this node AFTER merges. This will include
-   * no MergedProducer nodes, but all parents of the returned nodes will be Merged
-   * or the argument.
+   * Return the first dependants of this node AFTER merges and skipping Alsos.
+   * This will include no MergedProducer or AlsoProducer nodes, but all dependencies
```
Comment (ianoc) [inline summingbird-core/src/main/scala/com/twitter/summingbird/Dependants.scala]: s/all dependencies/all dependants ?

**Comment by ianoc** [comment]
LGTM, maybe minor comment update if the revision makes sense.

File: summingbird-core/src/main/scala/com/twitter/summingbird/Dependants.scala (hunk 3 above)
Comment (johnynek) [inline summingbird-core/src/main/scala/com/twitter/summingbird/Dependants.scala]: no, I think that is right. It is saying if you look up (towards dependencies) for all the returned nodes, they will either be Merged, Also or inp. I could add a test to verify that. In fact I should (but the test I added was related).

Comment (ianoc) [inline summingbird-core/src/main/scala/com/twitter/summingbird/Dependants.scala]: Yeah, seems right
